create table if not exists "user"
(
	user_id bigint generated by default as identity
		constraint user_pkey
			primary key
		constraint user_user_id_key
			unique,
	username varchar default ''::character varying not null,
	name varchar not null,
	birthdate timestamp with time zone not null,
	email varchar not null
		constraint user_email_key
			unique,
	password varchar not null,
	created_at timestamp with time zone default now() not null
);

create table if not exists customer
(
	customer_id bigint generated by default as identity
		constraint customer_pkey
			primary key
		constraint customer_customer_id_key
			unique,
	user_id bigint not null
		constraint customer_user_id_key
			unique
		constraint customer_user_id_fkey
			references "user",
	created_at timestamp with time zone default now() not null,
	new_cust_ind varchar default '''Y''::character varying'::character varying not null
);

create table if not exists product
(
	product_id bigint generated by default as identity
		constraint product_pkey
			primary key,
	created_at timestamp with time zone default now() not null,
	product_name varchar not null,
	color varchar not null,
	qty numeric default '0'::numeric not null,
	price numeric default '0'::numeric not null,
	product_img varchar not null,
	category varchar default ''::character varying not null
);

create table if not exists "order"
(
	order_id bigint generated by default as identity
		constraint order_pkey
			primary key,
	customer_id bigint not null
		constraint order_customer_id_fkey
			references customer,
	created_at timestamp with time zone default now() not null,
	defunct_ind varchar default 'N'::character varying not null
);

create table if not exists order_item
(
	order_item_id bigint generated by default as identity
		constraint order_item_pkey
			primary key,
	product_id bigint not null
		constraint order_item_product_id_fkey
			references product,
	order_id bigint not null
		constraint order_item_order_id_fkey
			references "order",
	order_qty numeric not null,
	created_at timestamp with time zone default now() not null,
	defunct_ind varchar default 'N'::character varying not null
);

create table if not exists invoice
(
	invoice_id bigint generated by default as identity
		constraint invoice_pkey
			primary key,
	invoice_date timestamp with time zone default now() not null,
	invoice_status varchar default 'UNPAID'::character varying not null,
	order_id bigint not null
		constraint invoice_order_id_fkey
			references "order"
);

create table if not exists payment
(
	payment_id bigint generated by default as identity
		constraint payment_pkey
			primary key,
	invoice_id bigint not null
		constraint payment_invoice_id_fkey
			references invoice,
	payment_amount numeric not null,
	created_at timestamp with time zone default now() not null
);

create table if not exists payment_method
(
	payment_method_id bigint generated by default as identity
		constraint payment_method_pkey
			primary key,
	customer_id bigint not null
		constraint payment_method_customer_id_fkey
			references customer,
	card_no numeric not null,
	card_holder varchar not null,
	expiration_month smallint not null,
	expiration_year integer not null,
	cvv integer not null,
	created_at timestamp with time zone default now() not null
);

create table if not exists shipment
(
	shipment_id bigint generated by default as identity
		constraint shipment_pkey
			primary key,
	invoice_id bigint not null
		constraint shipment_invoice_id_fkey
			references invoice,
	address varchar not null,
	province varchar not null,
	city varchar not null,
	created_at timestamp with time zone default now() not null
);

