### getPaymentMethodByCustomerId
GET http://localhost:3000/api/paymentMethod/getPaymentMethodByCustomerId/2
User-Agent: rest-client
Content-Type: application/json

### createPaymentMethod
POST http://localhost:3000/api/paymentMethod/createPaymentMethod
User-Agent: rest-client
Content-Type: application/json

{
    "customer_id": 2,
    "card_no": 1234567898765432,
    "card_holder": "DERIZHEESE",
    "expiration_month": "02",
    "expiration_year": "2024",
    "cvv": 2143
}