### getProducts
GET http://localhost:3000/api/product/getProducts
User-Agent: rest-client
Content-Type: application/json

### getProductById
GET http://localhost:3000/api/product/getProductById/4
User-Agent: rest-client
Content-Type: application/json

### getProductsByCategory
GET http://localhost:3000/api/product/getProductsByCategory/FORMAL
User-Agent: rest-client
Content-Type: application/json

### getProductsByName
GET http://localhost:3000/api/product/getProductsByName/bla
User-Agent: rest-client
Content-Type: application/json

### updateProductQty
PUT http://localhost:3000/api/product/updateProductQty
User-Agent: rest-client
Content-Type: application/json

{
    "product_id": 4,
    "qty": 8
}